version: '3.9'

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: hotel-web
    command: ./run_web.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - RUN_MIGRATE=true

  worker:
    build: .
    container_name: hotel-worker
    command: ./run_worker.sh
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - RUN_MIGRATE=false
