version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 hotel_admin.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - minio

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  db:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # S3 API 접근용
      - "9001:9001"  # 관리 콘솔 접근용

volumes:
  db_data:
  minio_data:
